#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 17 09:56:40 2021

@author: isaacspiller
"""

import turtle

s = turtle.getscreen()

a = turtle.Turtle() #left paddle
b = turtle.Turtle() #right paddle
c = turtle.Turtle() #ball

a.penup()
b.penup()
c.penup()

s.register_shape("paddle", ((0,0), (0, 100), (20,100), (20,0)))

a.shape("paddle")
b.shape("paddle")
c.shape("circle")

b.rt(90) #right paddle
a.rt(90) #left paddle
b.goto(300,0)
a.goto(-300,0)

leftMomentum = 0 #if momentum positive, move up. Negative, move down
rightMomentum = 0 #if momentum positive, move up. Negative, move down


def leftPaddleUp():
    global leftMomentum
    leftMomentum += 5
    a.bk(20)
    
def leftPaddleDown():
    global leftMomentum
    leftMomentum += -5

def rightPaddleUp():
    global rightMomentum
    rightMomentum += 5
    
def rightPaddleDown():
    global rightMomentum
    rightMomentum += -5
    
s.onkeypress(leftPaddleUp, 'w')
s.onkeypress(leftPaddleDown, 's')
s.onkeypress(rightPaddleUp, 'i')
s.onkeypress(rightPaddleDown, 'k')

a.bk(leftMomentum)
b.bk(rightMomentum)

s.listen()
turtle.done()





